[workspace]
resolver = "2"
members = [
  "crates/chess-core",
  "crates/chess",
  "crates/chess-cli",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/VitalyVorobyev/chess-rs"
