[workspace]
resolver = "2"
members = [
  "crates/chess-corners-core",
  "crates/chess-corners",
  "crates/chess-corners-ml",
  "crates/chess-corners-py",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/VitalyVorobyev/chess-corners-rs"
