[workspace]
resolver = "2"
members = [
  "crates/chess-core",
  "crates/chess",
  "tools/gen-golden",
  # phase later:
  # "crates/chess-cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/VitalyVorobyev/chess-rs"
